# Generated by Django 2.1.5 on 2019-02-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_resep', models.CharField(max_length=2)),
                ('kode_obat', models.CharField(max_length=3)),
                ('dosis', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('kode_dokter', models.CharField(max_length=1, primary_key='true', serialize=False)),
                ('nama_dokter', models.CharField(max_length=30)),
                ('spesialis', models.CharField(max_length=30)),
                ('alamat', models.CharField(max_length=100)),
                ('nomer', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_obat', models.CharField(max_length=5)),
                ('nama_obat', models.CharField(max_length=30)),
                ('jenis_obat', models.CharField(max_length=15)),
                ('kategori', models.CharField(max_length=50)),
                ('harga_obat', models.IntegerField()),
                ('jumlah_obat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('kode_pasien', models.CharField(max_length=6, primary_key='true', serialize=False)),
                ('nama_pasien', models.CharField(max_length=30)),
                ('alamat_pasien', models.CharField(max_length=100)),
                ('gender', models.BooleanField(max_length=2)),
                ('umur', models.CharField(max_length=2)),
                ('telepon', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('nomor_bayar', models.CharField(max_length=6)),
                ('kode_pasien', models.CharField(max_length=6, primary_key='true', serialize=False)),
                ('tanggal_bayar', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pendfataran',
            fields=[
                ('no_pendaftaran', models.CharField(max_length=1)),
                ('tanggal_pendaftaran', models.CharField(max_length=30)),
                ('kode_dokter', models.CharField(max_length=1, primary_key='true', serialize=False)),
                ('kode_pasien', models.CharField(max_length=100)),
                ('kode_polklinik', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Polklinik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_plk', models.CharField(max_length=2)),
                ('nama_plk', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer_resep', models.CharField(max_length=4)),
                ('kode_dokter', models.CharField(max_length=1)),
                ('kode_pasien', models.CharField(max_length=5)),
                ('kode_plk', models.CharField(max_length=2)),
            ],
        ),
    ]
